# Generated by Django 5.2.8 on 2025-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eprod',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('del_date', models.DateField()),
                ('del_charge', models.FloatField()),
                ('rating', models.FloatField()),
                ('del_stock', models.CharField(max_length=100)),
            ],
        ),
    ]
